Fixed bugs in `.github\workflows\ci.yml` file.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -207,13 +207,13 @@ jobs:
       - name: Check release type
         run:
           if [[ "${{ github.ref }}" = "refs/heads/${{ env.MAIN_BRANCH_NAME }}" && "${{ env.APP_VERSION_RELEASE }}" = "false" ]]; then
-            echo "The main branch cannot be used for non-release versions!"
-            exit 1
+            echo "The main branch cannot be used for non-release versions!";
+            exit 1;
           fi
 
           if [[ "${{ github.ref }}" = "refs/heads/${{ env.DEV_BRANCH_NAME }}" && "${{ env.APP_VERSION_RELEASE }}" = "true" ]]; then
-            echo "Use the main branch for the release build!"
-            exit 1
+            echo "Use the main branch for the release build!";
+            exit 1;
           fi
 
       - name: Set up Docker Buildx
@@ -276,7 +276,7 @@ jobs:
         echo "TAG_NAME=${{ env.APP_VERSION }}" >> $GITHUB_ENV
 
         if [[ "${{ github.ref }}" = "refs/heads/${{ env.DEV_BRANCH_NAME }}" && "${{ env.APP_VERSION_RELEASE }}" = "false" ]]; then
-          echo "PRERELEASE=true" >> $GITHUB_ENV
+          echo "PRERELEASE=true" >> $GITHUB_ENV;
         fi
 
     - name: Create release directory
